title: OData Filter Library
description: >-
  An OData standards based parser for building better REST APIs using
  the filter query parameter.
baseurl: "/odata-filter/"
url: "https://prior-art.github.io"
domain: "prior-art.github.io"
github_username:  prior-art

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

nav_enabled: true
search_enabled: true

color_scheme: dark

footer_content: "Copyright &copy; 2026 The OData Filter Authors."
