import { NodeType, BindingPower, ParseStrategy } from './types';
import { TokenType } from '../lexer/types';

export const nodeTypeLookup: Record<TokenType, NodeType> = {
  [TokenType.AND]: NodeType.LOGICAL_OPERATOR,
  [TokenType.OR]: NodeType.LOGICAL_OPERATOR,
  [TokenType.IN]: NodeType.COMPARISON_OPERATOR,
  [TokenType.EQ]: NodeType.COMPARISON_OPERATOR,
  [TokenType.NE]: NodeType.COMPARISON_OPERATOR,
  [TokenType.LT]: NodeType.COMPARISON_OPERATOR,
  [TokenType.LTE]: NodeType.COMPARISON_OPERATOR,
  [TokenType.GT]: NodeType.COMPARISON_OPERATOR,
  [TokenType.GTE]: NodeType.COMPARISON_OPERATOR,
  [TokenType.NOT]: NodeType.UNARY_OPERATOR,
  [TokenType.WHITESPACE]: NodeType.DEFAULT,
  [TokenType.STRING]: NodeType.STRING_LITERAL,
  [TokenType.NUMBER]: NodeType.NUMBER_LITERAL,
  [TokenType.TUPLE]: NodeType.ARRAY,
  [TokenType.SYMBOL]: NodeType.FIELD,
  [TokenType.OPEN_PAREN]: NodeType.DEFAULT,
  [TokenType.CLOSE_PAREN]: NodeType.DEFAULT,
  [TokenType.TRUE]: NodeType.BOOLEAN_LITERAL,
  [TokenType.FALSE]: NodeType.BOOLEAN_LITERAL,
  [TokenType.NULL]: NodeType.NULL,
  [TokenType.DATE]: NodeType.DATE_OBJECT,
  [TokenType.TIME]: NodeType.TIME_OBJECT,
  [TokenType.DATETIME]: NodeType.DATETIME_OBJECT,
  [TokenType.DURATION]: NodeType.DURATION_OBJECT,
};

export const bindingPowerLookup: Record<TokenType, BindingPower> = {
  [TokenType.AND]: BindingPower.LOGICAL,
  [TokenType.OR]: BindingPower.LOGICAL,
  [TokenType.IN]: BindingPower.COMPARISON,
  [TokenType.EQ]: BindingPower.COMPARISON,
  [TokenType.NE]: BindingPower.COMPARISON,
  [TokenType.LT]: BindingPower.COMPARISON,
  [TokenType.LTE]: BindingPower.COMPARISON,
  [TokenType.GT]: BindingPower.COMPARISON,
  [TokenType.GTE]: BindingPower.COMPARISON,
  [TokenType.NOT]: BindingPower.LOGICAL,
  [TokenType.WHITESPACE]: BindingPower.DEFAULT,
  [TokenType.STRING]: BindingPower.LITERAL,
  [TokenType.NUMBER]: BindingPower.LITERAL,
  [TokenType.TUPLE]: BindingPower.LITERAL,
  [TokenType.SYMBOL]: BindingPower.LITERAL,
  [TokenType.OPEN_PAREN]: BindingPower.DEFAULT,
  [TokenType.CLOSE_PAREN]: BindingPower.DEFAULT,
  [TokenType.TRUE]: BindingPower.LITERAL,
  [TokenType.FALSE]: BindingPower.LITERAL,
  [TokenType.NULL]: BindingPower.LITERAL,
  [TokenType.DATE]: BindingPower.LITERAL,
  [TokenType.TIME]: BindingPower.LITERAL,
  [TokenType.DATETIME]: BindingPower.LITERAL,
  [TokenType.DURATION]: BindingPower.LITERAL,
};

export const parseStrategyLookup: Record<TokenType, ParseStrategy> = {
  [TokenType.AND]: ParseStrategy.LED,
  [TokenType.OR]: ParseStrategy.LED,
  [TokenType.IN]: ParseStrategy.LED,
  [TokenType.EQ]: ParseStrategy.LED,
  [TokenType.NE]: ParseStrategy.LED,
  [TokenType.LT]: ParseStrategy.LED,
  [TokenType.LTE]: ParseStrategy.LED,
  [TokenType.GT]: ParseStrategy.LED,
  [TokenType.GTE]: ParseStrategy.LED,
  [TokenType.NOT]: ParseStrategy.NUD,
  [TokenType.WHITESPACE]: ParseStrategy.DEFAULT,
  [TokenType.TUPLE]: ParseStrategy.NUD,
  [TokenType.STRING]: ParseStrategy.NUD,
  [TokenType.NUMBER]: ParseStrategy.NUD,
  [TokenType.SYMBOL]: ParseStrategy.NUD,
  [TokenType.OPEN_PAREN]: ParseStrategy.NUD,
  [TokenType.CLOSE_PAREN]: ParseStrategy.DEFAULT,
  [TokenType.TRUE]: ParseStrategy.NUD,
  [TokenType.FALSE]: ParseStrategy.NUD,
  [TokenType.NULL]: ParseStrategy.NUD,
  [TokenType.DATE]: ParseStrategy.NUD,
  [TokenType.TIME]: ParseStrategy.NUD,
  [TokenType.DATETIME]: ParseStrategy.NUD,
  [TokenType.DURATION]: ParseStrategy.NUD,
};
