name: Deploy GitHub Page (Jekyll) Docs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./packages/docs
          destination: ./package/docs/_site
          verbose: true
