name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run-diff:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.diffs.outputs.core_any_changed }}
      fastify: ${{ steps.diffs.outputs.fastify_any_changed }}
      project_root: ${{ steps.diffs.outputs.project_root_any_changed }}
      cli: ${{ steps.diffs.outputs.cli_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@8c4da285a3cb8b621b4a5cc251d6282b4b0a67a5
        id: diffs
        with:
          files_yaml: |
            project_root:
              - '.github/**'
              - 'tsconfig.json'
              - 'package.json'
              - 'package-lock.json'
              - '.nvmrc'
              - 'eslint.config.js'
            core:
              - 'packages/core/**'
            assemblyscript_regex:
              - 'packages/assemblyscript-regex/**'
            core_wasm:
              - 'packages/core-wasm/**'
            fastify:
              - 'packages/fastify/**'
            cli:
              - 'packages/cli/**'
            marshalers:
              - 'packages/marshalers/**'
            validation:
              - 'packages/validation/**'

  core:
    needs: run-diff
    if: needs.run-diff.outputs.core == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'core'

  assemblyscript-regex:
    needs: run-diff
    if: needs.run-diff.outputs.assemblyscript_regex == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'assemblyscript-regex'
      mutation: false
      coverage: false

  core-wasm:
    needs: run-diff
    if: needs.run-diff.outputs.core_wasm == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'core-wasm'
      mutation: false
      coverage: false

  fastify:
    needs: run-diff
    if: needs.run-diff.outputs.fastify == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'fastify'

  cli:
    needs: run-diff
    if: needs.run-diff.outputs.cli == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'cli'

  marshalers:
    needs: run-diff
    if: needs.run-diff.outputs.marshalers == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'marshalers'

  validation:
    needs: run-diff
    if: needs.run-diff.outputs.validation == 'true' || needs.run-diff.outputs.project_root == 'true'
    uses: prior-art/odata-filter/.github/workflows/ci-checks.yml@main
    secrets: inherit
    with:
      package: 'validation'
